project:
  type: website
  output-dir: _site
  
website:
  title: "CSAMA 2025 Biological Data Science"
  open-graph:
     locale:
       en_US
     site-name:
       "CSAMA 2025"
  navbar:
    title: false
    background: "#1a81c2"
    foreground: "white"
    logo: "images/CSAMA2025.png"
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: programme.qmd
        text: Programme
      - href: registration.qmd
        text: Registration
      - href: venue.qmd
        text: Venue
      - href: travel-and-accommodation.qmd
        text: Travel and Accommodation
      - href: code.qmd
        text: Code of Conduct
      - href: contacts.qmd
        text: Contacts
  page-footer: 
    left: "Copyright (c) 2025, European Bioconductor Society e.V. </br>
  The European Bioconductor Society e.V. is 
  a registered association in Germany created to support 
  Bioconductor's mission to promote open source software 
  in the life sciences and statistics."
  favicon: "images/CSAMA2025.png"
  image: "images/CSAMA2025.png"

format:
  html:
    theme:
      - materia
    css: styles.css
    linkcolor: "#2A57A3"
    toc-color: "#2A57A3"
    toc: true
    grid:
      sidebar-width: 150px
      body-width: 750px
      margin-width: 300px
    date-format: iso
    include-in-header:
      - text: |
          <meta http-equiv="Cache-Control" content="max-age=1800, must-revalidate"> 
    lightbox: true
    
